package br.com.pucsp.projetointegrador.utils;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class AddressData {
	private AddressData () {}
	
	public static List<String> streetType() {
		List<String> streetType = new ArrayList<String>();
		streetType.add("Área");
		streetType.add("Acesso");
		streetType.add("Acampamento");
		streetType.add("Acesso Local");
		streetType.add("Adro");
		streetType.add("Área Especial");
		streetType.add("Aeroporto");
		streetType.add("Alameda");
		streetType.add("Avenida Marginal Direita");
		streetType.add("Avenida Marginal Esquerda");
		streetType.add("Anel Viário");
		streetType.add("Antiga Estrada");
		streetType.add("Artéria");
		streetType.add("Alto");
		streetType.add("Atalho");
		streetType.add("Área Verde");
		streetType.add("Avenida");
		streetType.add("Avenida Contorno");
		streetType.add("Avenida Marginal");
		streetType.add("Avenida Velha");
		streetType.add("Balneário");
		streetType.add("Beco");
		streetType.add("Buraco");
		streetType.add("Belvedere");
		streetType.add("Bloco");
		streetType.add("Balão");
		streetType.add("Blocos");
		streetType.add("Bulevar");
		streetType.add("Bosque");
		streetType.add("Boulevard");
		streetType.add("Baixa");
		streetType.add("Cais");
		streetType.add("Calçada");
		streetType.add("Caminho");
		streetType.add("Canal");
		streetType.add("Chácara");
		streetType.add("Chapadão");
		streetType.add("Ciclovia");
		streetType.add("Circular");
		streetType.add("Conjunto");
		streetType.add("Conjunto Mutirão");
		streetType.add("Complexo Viário");
		streetType.add("Colônia");
		streetType.add("Comunidade");
		streetType.add("Condomínio");
		streetType.add("Corredor");
		streetType.add("Campo");
		streetType.add("Córrego");
		streetType.add("Contorno");
		streetType.add("Descida");
		streetType.add("Desvio");
		streetType.add("Distrito");
		streetType.add("Entre Bloco");
		streetType.add("Estrada Intermunicipal");
		streetType.add("Enseada");
		streetType.add("Entrada Particular");
		streetType.add("Entre Quadra");
		streetType.add("Escada");
		streetType.add("Escadaria");
		streetType.add("Estrada Estadual");
		streetType.add("Estrada Vicinal");
		streetType.add("Estrada de Ligação");
		streetType.add("Estrada Municipal");
		streetType.add("Esplanada");
		streetType.add("Estrada de Servidão");
		streetType.add("Estrada");
		streetType.add("Estrada Velha");
		streetType.add("Estrada Antiga");
		streetType.add("Estação");
		streetType.add("Estádio");
		streetType.add("Estância");
		streetType.add("Estrada Particular");
		streetType.add("Estacionamento");
		streetType.add("Evangélica");
		streetType.add("Elevada");
		streetType.add("Eixo Industrial");
		streetType.add("Favela");
		streetType.add("Fazenda");
		streetType.add("Ferrovia");
		streetType.add("Fonte");
		streetType.add("Feira");
		streetType.add("Forte");
		streetType.add("Galeria");
		streetType.add("Granja");
		streetType.add("Núcleo Habitacional");
		streetType.add("Ilha");
		streetType.add("Indeterminado");
		streetType.add("Ilhota");
		streetType.add("Jardim");
		streetType.add("Jardinete");
		streetType.add("Ladeira");
		streetType.add("Lagoa");
		streetType.add("Lago");
		streetType.add("Loteamento");
		streetType.add("Largo");
		streetType.add("Lote");
		streetType.add("Mercado");
		streetType.add("Marina");
		streetType.add("Modulo");
		streetType.add("Projeção");
		streetType.add("Morro");
		streetType.add("Monte");
		streetType.add("Núcleo");
		streetType.add("Núcleo Rural");
		streetType.add("Outeiro");
		streetType.add("Paralela");
		streetType.add("Passeio");
		streetType.add("Pátio");
		streetType.add("Praça");
		streetType.add("Praça de Esportes");
		streetType.add("Parada");
		streetType.add("Paradouro");
		streetType.add("Ponta");
		streetType.add("Praia");
		streetType.add("Prolongamento");
		streetType.add("Parque Municipal");
		streetType.add("Parque");
		streetType.add("Parque Residencial");
		streetType.add("Passarela");
		streetType.add("Passagem");
		streetType.add("Passagem de Pedestre");
		streetType.add("Passagem Subterrânea");
		streetType.add("Ponte");
		streetType.add("Porto");
		streetType.add("Quadra");
		streetType.add("Quinta");
		streetType.add("Quintas");
		streetType.add("Rua");
		streetType.add("Rua Integração");
		streetType.add("Rua de Ligação");
		streetType.add("Rua Particular");
		streetType.add("Rua Velha");
		streetType.add("Ramal");
		streetType.add("Recreio");
		streetType.add("Recanto");
		streetType.add("Retiro");
		streetType.add("Residencial");
		streetType.add("Reta");
		streetType.add("Ruela");
		streetType.add("Rampa");
		streetType.add("Rodo Anel");
		streetType.add("Rodovia");
		streetType.add("Rotula");
		streetType.add("Rua de Pedestre");
		streetType.add("Margem");
		streetType.add("Retorno");
		streetType.add("Rotatória");
		streetType.add("Segunda Avenida");
		streetType.add("Sitio");
		streetType.add("Servidão");
		streetType.add("Setor");
		streetType.add("Subida");
		streetType.add("Trincheira");
		streetType.add("Terminal");
		streetType.add("Trecho");
		streetType.add("Trevo");
		streetType.add("Túnel");
		streetType.add("Travessa");
		streetType.add("Travessa Particular");
		streetType.add("Travessa Velha");
		streetType.add("Unidade");
		streetType.add("Via");
		streetType.add("Via Coletora");
		streetType.add("Via Local");
		streetType.add("Via de Acesso");
		streetType.add("Vala");
		streetType.add("Via Costeira");
		streetType.add("Viaduto");
		streetType.add("Via Expressa");
		streetType.add("Vereda");
		streetType.add("Via Elevado");
		streetType.add("Vila");
		streetType.add("Viela");
		streetType.add("Vale");
		streetType.add("Via Litorânea");
		streetType.add("Via de Pedestre");
		streetType.add("Variante");
		streetType.add("Zigue-Zague");
		
		return streetType;
	}
	
	public static Map<String, String> states() {
		Map<String, String> states = new HashMap<String, String>();
		states.put("RO", "Rondônia");
		states.put("AC", "Acre");
		states.put("AM", "Amazonas");
		states.put("RR", "Roraima");
		states.put("PA", "Pará");
		states.put("AP", "Amapá");
		states.put("TO", "Tocantins");
		states.put("MA", "Maranhão");
		states.put("PI", "Piauí");
		states.put("CE", "Ceará");
		states.put("RN", "Rio Grande do Norte");
		states.put("PB", "Paraíba");
		states.put("PE", "Pernambuco");
		states.put("AL", "Alagoas");
		states.put("SE", "Sergipe");
		states.put("BA", "Bahia");
		states.put("MG", "Minas Gerais");
		states.put("ES", "Espírito Santo");
		states.put("RJ", "Rio de Janeiro");
		states.put("SP", "São Paulo");
		states.put("PR", "Paraná");
		states.put("SC", "Santa Catarina");
		states.put("RS", "Rio Grande do Sul (*)");
		states.put("MS", "Mato Grosso do Sul");
		states.put("MT", "Mato Grosso");
		states.put("GO", "Goiás");
		states.put("DF", "Distrito Federal");
		
		return states;
	}
}